### ISSUE TITLE
Syntax error: invalid syntax

### ISSUE THREAD

**Issue by originalsaroj** [naryal2580/naryal2580#3]
line 168
    print('\033[H\033[J', end='')
                             ^

**Comment by naryal2580** [comment]
@originalsaroj Thank you so much for the issues. Could you please be more verbose, like steps to produce the error. And, OS you are using as well as python version you are using.

**Comment by originalsaroj** [comment]
it was python version problem, i was using 2.7.15+ in ubuntu but got it right after installation of python3 ..
but now it shows another error saying that,
Python/style.py", line 5, in <module>
    from ctypes import windll
ImportError: cannot import name 'windll'

**Comment by naryal2580** [comment]
Okay, fixing it!
